### ISSUE TITLE
Wanted change in common?

### ISSUE THREAD

**Issue by mbaldessari** [validatedpatterns/regional-resiliency-pattern#5]
Hi @TomerFi @r2dedios , I was trying to update common in this pattern and I noticed this difference:
```
  cloud: {{ $cloud }}
    region: '{{ $region }}'
    vendor: OpenShift
-    cluster.open-cluster-management.io/clusterset: {{ .name }}
+    cluster.open-cluster-management.io/clusterset: {{ $group.name }}
spec:
  {{- if .size }}
```

Do we need a change like this in proper common, or can we drop this ?
Thanks,
Michele

**Comment by TomerFi** [comment]
Hi @mbaldessari 
This look familliar! What file is this in?

**Comment by TomerFi** [comment]
If I remember correctly, the same context also has a `$group = .` somewhere. So, there's a chance this was done for consistency.

**Comment by mbaldessari** [comment]
Hi @TomerFi , apologies I missed to copy the file name. It is https://github.com/validatedpatterns/regional-resiliency-pattern/blob/main/common/acm/templates/provision/clusterpool.yaml#L47. I'll push a change to use `$group.name` in proper common and put you in CC. From a quick look it does look sane
